#!/bin/bash
rm BQN8.jar
rm -rf classes
mkdir classes
javac -Xmaxerrs 1000 --release 8 -d ./classes $(find srcm -name '*.java')
cd classes
jar cvfe BQN8.jar APL.Main . > /dev/null
mv BQN8.jar ../BQN8.jar
cd ..
cp BQN8.jar ../code/BQN8.jar
rm -rf classes
