#!/bin/bash
rm -f BQN.jar
rm -rf src/build/BQN
cd src
mkdir -p build
javac -Xmaxerrs 1000 -d ./build $(find APL -name '*.java')
cd build
jar cvfe BQN.jar APL.Main * > /dev/null
mv BQN.jar ../../BQN.jar
