#!/usr/bin/env bash
rm -f BQN.jar
mkdir -p classes
javac -encoding UTF-8 -d ./classes $(find src -name '*.java')
cd classes
jar cvfe BQN.jar BQN.Main * > /dev/null
mv BQN.jar ../BQN.jar
cd ..
rm -rf classes